# Generated by Django 5.1.2 on 2024-11-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_article_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
